config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  # get 'sessions/new'
  # get 'users/new'
  root 'static_pages#home'
  get '/help',to: 'static_pages#help'
  get '/about',to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'
  # get '/microposts', to: 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
  end
  post 'microposts/share', to: 'microposts#share'
  post 'mlikes/show', to: 'mlikes#show'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :mlikes, only: [:create, :destroy, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'application#hello'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image,
content_type: { in: %w[image/jpeg image/gif image/png],
                          message: "must be a valid image format" },
                          size:{ less_than: 5.megabytes,
                                  message:"should be less than 5MB" }
has_many :mlikes
  # Returns a resized image for display.
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy
    def create
        @micropost = current_user.microposts.build(microposts_params)
        @micropost.image.attach(params[:micropost][:image])
        if @micropost.save
            flash[:success] = "Micropost created"
            redirect_to root_url
        else
            @feed_items = current_user.feed.paginate(page: params[:page])
            render 'static_pages/home'
        end
    end
    

    def share
        @micropost = current_user.microposts.build(content: Micropost.find(params[:share_id]).content)
        if @micropost.save
            redirect_to current_user
        else
            redirect_to root_url
        end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        if request.referrer.nil? || request.referrer == microposts_url
            redirect_to root_url
        else
            redirect_to request.referrer
        end
    end

    private
     def microposts_params
        params.require(:micropost).permit(:content, :image)
     end

     def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
     end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content">
        <%= micropost.content %>
        <%= image_tag micropost.display_image if micropost.image.attached? %>
    </span>

    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user?(micropost.user) %>
        <%= link_to "delete", micropost, method: :delete,   
                                                    data: { confirm: "You sure?" } %>
        <% end %>
        </span>
        <% if !current_user?(micropost.user) %>  
            <%= form_with(model: @micropost, url: microposts_share_path, local: true) do |f| %>
                <%= hidden_field_tag :share_id, micropost.id  %>
                <%= f.submit "share", class: "btn btn-primary" %>
            <% end %>
           <% end %>
           <%= micropost.mlikes.count %> Likes
           <%= form_with(model: @mlike, url: mlikes_show_path, local: true) do |f| %>
            <%= hidden_field_tag :viewlike_id, micropost.id  %>
            <%= f.submit "View_likes", class: "btn btn-primary" %>
            <% end %>
           <% if !current_user?(micropost.user) %>
           <% mlike = current_user.mlikes.find_by(micropost: micropost) %>
           <%if  mlike.nil? %>
           <%= button_to "Like", mlikes_path, params: { mlike: {micropost_id: micropost.id}}, method: :post %>
           <% else %>
           <%= button_to "Unlike", mlike_path(mlike), method: :delete %>
           <% end %>
                
           <% end %>
    
    
</li>